export default {
	xl: {
		fontSize: 27,
		lineHeight: 36,
		fontWeight: '500',
		color: 'text',
		fontFamily: 'Roboto-Regular',
	},
	l: {
		fontSize: 24,
		lineHeight: 28,
		fontWeight: '500',
		color: 'text',
		fontFamily: 'Roboto-Regular',
	},
	m: {
		fontSize: 20,
		lineHeight: 28,
		fontWeight: '600',
		color: 'text',
		fontFamily: 'Roboto-Regular',
	},
	s: {
		fontSize: 16,
		lineHeight: 24,
		fontWeight: '400',
		color: 'text',
		fontFamily: 'Roboto-Regular',
	},
	heading: {
		fontSize: 17,
		lineHeight: 19,
		fontWeight: '700',
		color: 'text',
		fontFamily: 'Roboto-Regular',
	},
	subHeading: {
		fontSize: 13,
		lineHeight: 16,
		fontWeight: '600',
		color: 'text',
		fontFamily: 'Roboto-Regular',
	},
	title: {
		fontSize: 16,
		lineHeight: 20,
		fontWeight: '500',
		color: 'text',
		fontFamily: 'Roboto-Regular',
	},
	body: {
		fontSize: 15,
		lineHeight: 17,
		fontWeight: '400',
		color: 'text',
		fontFamily: 'Roboto-Regular',
	},
	bodyBold: {
		fontSize: 15,
		lineHeight: 18,
		fontWeight: '700',
		color: 'text',
		fontFamily: 'Roboto-Regular',
	},
	bodyMedium: {
		fontSize: 15,
		lineHeight: 18,
		fontWeight: '500',
		color: 'text',
		fontFamily: 'Roboto-Medium',
	},
	caption: {
		fontSize: 11,
		lineHeight: 18,
		fontWeight: '500',
		color: 'text',
		fontFamily: 'Roboto-Regular',
	},
	captionItalic: {
		fontSize: 12,
		lineHeight: 18,
		fontWeight: '600',
		color: 'text',
		fontFamily: 'Roboto-Italic',
	},
	captionBold: {
		fontSize: 12,
		lineHeight: 18,
		fontWeight: '700',
		color: 'text',
		fontFamily: 'Roboto-Regular',
	},
	large: {
		fontSize: 30,
		fontWeight: '700',
		color: 'text',
		lineHeight: 35,
		fontFamily: 'Roboto-Regular',
	},
	button: {
		fontSize: 14,
		lineHeight: 16,
		fontWeight: '500',
		color: 'white',
		fontFamily: 'Roboto-Regular',
	},
	smallItalic: {
		fontSize: 11,
		lineHeight: 13,
		fontWeight: '500',
		color: 'text',
		fontFamily: 'Roboto-ThinItalic',
	},
	H1: {
		fontSize: 32,
		lineHeight: 42,
		fontWeight: '700',
		color: 'white',
		fontFamily: 'Roboto-Regular',
	},
	inputLabel: {
		fontFamily: 'Roboto',
		fontWeight: '400',
		fontSize: 11,
		lineHeight: 16,
		letterSpacing: 1.5,
	},
	inputText: {
		fontFamily: 'Roboto',
		fontWeight: '400',
		fontSize: 14,
	},
};
