export default {
	example: { backgroundColor: 'green', padding: 's' },
	buttonShadow: {
		borderRadius: 's',
		height: 46,
		width: '100%',
		shadowColor: 'black',
		shadowOffset: {
			width: 1,
			height: 1,
		},
		shadowOpacity: 0.32,
		shadowRadius: 2,
		elevation: 0,
		backgroundColor: 'transparent',
		// justifyContent: 'center',
		// alignItems: 'center',
		// alignSelf: 'center',
	},
	buttonTransparent: {
		backgroundColor: 'transparent_white',
		justifyContent: 'center',
		alignItems: 'center',
		alignSelf: 'center',
		borderWidth: 1,
		borderColor: 'smokeWhite',
		width: '100%',
		height: 36,
		borderRadius: 's',
	},
	buttonSelection: {
		borderRadius: 'm',
		marginVertical: 'xxs',
		paddingHorizontal: 'm',
		height: 55,
		width: '100%',
		backgroundColor: 'solitude',
		flexDirection: 'row',
		justifyContent: 'space-between',
		alignItems: 'center',
	},
	buttonOutline: {
		borderRadius: 's',
		borderColor: 'primary',
		borderWidth: 1,
		height: 36,
		width: '100%',
		backgroundColor: 'transparent',
		justifyContent: 'center',
		alignItems: 'center',
	},
};
